services:
  nodejs:
    build: ./nodejs
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=products_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OTEL_SERVICE_NAME=nodejs-product-service
      - OTEL_EXPORTER_OTLP=http://jaeger:4317/v1/traces
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"] 
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=products_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ./mysql/tables.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql/data.sql:/docker-entrypoint-initdb.d/2.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis:8
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  nodejs-api-test:
    image: postman/newman:alpine
    tty: true
    stdin_open: true
    command:
      run nodejs.postman_collection.json -k
      -r cli,junit
      --reporter-junit-export="reports/results.xml"
    volumes:
      - ./postman/:/etc/newman
    depends_on:
      nodejs:
        condition: service_healthy
  
  # otel-collector:
  #   image: grafana/otel-lgtm
  #   ports:
  #     - "4317:4317"
  #     - "4318:4318"
  #     - "4000:3000"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      # - 4317:4317
      # - 4318:4318
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"