scrape_configs:
  - job_name: 'service-a'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nodejs:3000']
        labels:
          application: 'nodejs-product-service'